
CREATE TABLE IF NOT EXISTS user (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	first_name VARCHAR NOT NULL,
	last_name VARCHAR NOT NULL,
	email VARCHAR (50) UNIQUE,
	password VARCHAR(60),
	auth_token VARCHAR(60),
	created_at INT NOT NULL
);


CREATE TABLE IF NOT EXISTS blog (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	title VARCHAR (150) NOT NULL,
	content TEXT NOT NULL,
	author INTEGER NOT NULL REFERENCES users (id),
	created_at INT NOT NULL
);
